<a href="https://colab.research.google.com/github/rund-omari/Data.Eng3/blob/main/lectures/lecture_02/Lecture_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
!pip install  openpyxl pyarrow

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.13/dist-packages (23.0.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [1]:
import pandas as pd

In [2]:
data = {
    "name": ["Ahmad", "Sara", "Lara"],
    "age": [25, 28, 22],
    "city": ["Amman", "Irbid", "Amman"]
}

In [8]:
df = pd.DataFrame(data)
print(df)
print(type(df))

    name  age   city
0  Ahmad   25  Amman
1   Sara   28  Irbid
2   Lara   22  Amman
<class 'pandas.core.frame.DataFrame'>

In [18]:
type(df['age'])
df['age']

0    25
1    28
2    22
Name: age, dtype: int64

In [15]:
df[['age','name']]

   age   name
0   25  Ahmad
1   28   Sara
2   22   Lara

In [20]:
data = {
    "customer_id": [101, 102, 103, 104, 105, 106],
    "name": ["Ahmad", "Sara", "Lara", "Omar", "Noor", "Zaid"],
    "age": [25, 28, 22, 35, 31, 29],
    "city": ["Amman", "Irbid", "Amman", "Zarqa", "Amman", "Irbid"],
    "salary": [900, 1200, 1000, 1500, None, 1100],
    "active": [True, False, True, True, False, True]
}

In [22]:
df2 = pd.DataFrame(data)
df2

   customer_id   name  age   city  salary  active
0          101  Ahmad   25  Amman   900.0    True
1          102   Sara   28  Irbid  1200.0   False
2          103   Lara   22  Amman  1000.0    True
3          104   Omar   35  Zarqa  1500.0    True
4          105   Noor   31  Amman     NaN   False
5          106   Zaid   29  Irbid  1100.0    True

In [24]:
df2.to_csv('/content/customer_data.csv')

In [26]:
df2.to_excel('/content/customer_data.xlsx',index = False)

In [28]:
df2.to_json('/content/customer_data.json' , orient = 'records',indent = 2)

In [34]:
df2.to_parquet('/content/customer_data.parquet' , index = False, engine='pyarrow')

In [35]:
csv_df = pd.read_csv("/content/customer_data.csv")

excel_df = pd.read_excel("/content/customer_data.xlsx")

json_df = pd.read_json(
    "/content/customer_data.json",
    orient="records"
)

parquet_df = pd.read_parquet("/content/customer_data.parquet",engine='pyarrow')

In [39]:
excel_df

   customer_id   name  age   city  salary  active
0          101  Ahmad   25  Amman   900.0    True
1          102   Sara   28  Irbid  1200.0   False
2          103   Lara   22  Amman  1000.0    True
3          104   Omar   35  Zarqa  1500.0    True
4          105   Noor   31  Amman     NaN   False
5          106   Zaid   29  Irbid  1100.0    True

In [41]:
excel_df.head()
excel_df.head(3)

   customer_id   name  age   city  salary  active
0          101  Ahmad   25  Amman   900.0    True
1          102   Sara   28  Irbid  1200.0   False
2          103   Lara   22  Amman  1000.0    True

In [43]:
excel_df.tail(3)

   customer_id  name  age   city  salary  active
3          104  Omar   35  Zarqa  1500.0    True
4          105  Noor   31  Amman     NaN   False
5          106  Zaid   29  Irbid  1100.0    True

In [44]:
excel_df.shape

(6, 6)

In [45]:
excel_df.columns

Index(['customer_id', 'name', 'age', 'city', 'salary', 'active'], dtype='object')

In [46]:
excel_df.dtypes

customer_id      int64
name            object
age              int64
city            object
salary         float64
active            bool
dtype: object

In [47]:
excel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  6 non-null      int64
 1   name         6 non-null      object
 2   age          6 non-null      int64
 3   city         6 non-null      object
 4   salary       5 non-null      float64
 5   active       6 non-null      bool
dtypes: bool(1), float64(1), int64(2), object(2)
memory usage: 378.0+ bytes

In [50]:
excel_df.describe(include='all')
excel_df.describe(include='object')

         name   city
count       6      6
unique      6      3
top     Ahmad  Amman
freq        1      3