In [ ]:
import pandas as pd
data=pd.read_csv("/content/jordan_ecommerce_raw (1).csv")

هون قرات الداتا

In [ ]:
data.head()

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
0,ORD-1001,CUS-027,Zarqa,Fashion,52.50,1,2026-06-17,Card,26,NaN
1,ORD-1002,CUS-051,Irbid,Fashion,33.40,2,2026-08-16,CliQ,3,1.0
2,ORD-1003,CUS-076,Aqaba,Fashion,29.50,1,2026-06-12,CliQ,2,3.0
3,ORD-1004,CUS-036,Irbid,Electronics,23.19,2,2026-08-31,Card,1,5.0
4,ORD-1005,CUS-075,Salt,Beauty,84.28,5,2026-05-31,CliQ,1,NaN

عرضت اول خمس صفوف

In [ ]:
data.shape

(413, 10)

عرضت كم صف وكم عمود عندي

In [ ]:
data.columns

Index(['order_id', 'customer_id', 'city', 'category', 'order_amount',
       'quantity', 'order_date', 'payment_method', 'delivery_days',
       'customer_rating'],
      dtype='object')

هون عرضنا اسماء جميع الاعمده الي بالداتا

In [ ]:
data.dtypes

order_id            object
customer_id         object
city                object
category            object
order_amount       float64
quantity             int64
order_date          object
payment_method      object
delivery_days        int64
customer_rating    float64
dtype: object

عرضت نوع البيانات لكل عمود

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         413 non-null    object
 1   customer_id      413 non-null    object
 2   city             390 non-null    object
 3   category         413 non-null    object
 4   order_amount     396 non-null    float64
 5   quantity         413 non-null    int64
 6   order_date       413 non-null    object
 7   payment_method   400 non-null    object
 8   delivery_days    413 non-null    int64
 9   customer_rating  367 non-null    float64
dtypes: float64(2), int64(2), object(6)
memory usage: 32.4+ KB

ملخص ومعلومات عن البيانات

In [ ]:
data.describe()

       order_amount    quantity  delivery_days  customer_rating
count    396.000000  413.000000     413.000000       367.000000
mean      74.218434    2.970944       2.677966         2.989101
std      270.877718    1.479349       2.809558         1.561102
min      -56.080000   -1.000000       1.000000         1.000000
25%       23.062500    2.000000       1.000000         2.000000
50%       38.240000    3.000000       2.000000         3.000000
75%       65.037500    4.000000       3.000000         4.000000
max     3499.810000    5.000000      26.000000         8.000000

بعرض الاحصلءات للاعمده

In [ ]:
data["order_id"]

0      ORD-1001
1      ORD-1002
2      ORD-1003
3      ORD-1004
4      ORD-1005
         ...
408    ORD-1056
409    ORD-1111
410    ORD-1250
411    ORD-1319
412    ORD-1011
Name: order_id, Length: 413, dtype: object

هون عرضت سيريز يعني اكثر من صف وعامود واحد فقط

In [ ]:
data[["order_id","order_amount"]]

     order_id  order_amount
0    ORD-1001         52.50
1    ORD-1002         33.40
2    ORD-1003         29.50
3    ORD-1004         23.19
4    ORD-1005         84.28
..        ...           ...
408  ORD-1056          9.01
409  ORD-1111         73.64
410  ORD-1250          9.93
411  ORD-1319         39.03
412  ORD-1011        999.00

[413 rows x 2 columns]

عرضت داتافريم اكثر من عمود

In [ ]:
data[data["city"] == "irbid"]

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
6,ORD-1007,CUS-043,irbid,Home,144.19,1,2026-03-27,Card,4,NaN
28,ORD-1029,CUS-054,irbid,Beauty,31.93,5,2026-07-24,Cash,1,4.0
323,ORD-1324,CUS-135,irbid,Books,24.81,5,2026-01-01,Cash,2,3.0
397,ORD-1398,CUS-055,irbid,Electronics,22.47,2,2026-08-03,Cash,6,3.0

حطيت شرط يعرض البيانات الي المدينه فيهم بتكون اربد

In [ ]:

data[data["order_amount"] >= 50]

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
0,ORD-1001,CUS-027,Zarqa,Fashion,52.50,1,2026-06-17,Card,26,NaN
4,ORD-1005,CUS-075,Salt,Beauty,84.28,5,2026-05-31,CliQ,1,NaN
6,ORD-1007,CUS-043,irbid,Home,144.19,1,2026-03-27,Card,4,NaN
10,ORD-1011,CUS-089,Aqaba,Beauty,85.36,4,2026-02-03,CliQ,2,3.0
12,ORD-1013,CUS-141,Aqaba,Books,66.58,3,2026-05-18,Card,5,5.0
...,...,...,...,...,...,...,...,...,...,...
403,ORD-1265,CUS-149,Aqaba,Books,88.19,4,2026-02-19,Card,1,5.0
404,ORD-1027,CUS-113,Salt,Electronics,129.03,1,2026-03-31,CliQ,3,2.0
407,ORD-1163,CUS-068,Salt,Home,72.90,2,2026-09-12,Cash,2,2.0
409,ORD-1111,CUS-009,Irbid,Fashion,73.64,5,2026-03-24,Card,2,3.0
412,ORD-1011,CUS-089,Aqaba,Beauty,999.00,4,2026-02-03,CliQ,2,3.0

عرضنا البيانات الي كميه الاوردير فيهم اكبر او بتساوي 50