<a href="https://colab.research.google.com/github/rund-omari/Data.Eng3/blob/main/lectures/Lecture_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data=pd.read_csv("/content/jordan_ecommerce_raw.csv")

In [ ]:
data.head()

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
0,ORD-1001,CUS-027,Zarqa,Fashion,52.50,1,2026-06-17,Card,26,NaN
1,ORD-1002,CUS-051,Irbid,Fashion,33.40,2,2026-08-16,CliQ,3,1.0
2,ORD-1003,CUS-076,Aqaba,Fashion,29.50,1,2026-06-12,CliQ,2,3.0
3,ORD-1004,CUS-036,Irbid,Electronics,23.19,2,2026-08-31,Card,1,5.0
4,ORD-1005,CUS-075,Salt,Beauty,84.28,5,2026-05-31,CliQ,1,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         413 non-null    object
 1   customer_id      413 non-null    object
 2   city             390 non-null    object
 3   category         413 non-null    object
 4   order_amount     396 non-null    float64
 5   quantity         413 non-null    int64
 6   order_date       413 non-null    object
 7   payment_method   400 non-null    object
 8   delivery_days    413 non-null    int64
 9   customer_rating  367 non-null    float64
dtypes: float64(2), int64(2), object(6)
memory usage: 32.4+ KB

In [52]:
# @title
data.describe()

,order_amount,quantity,order_date,delivery_days,customer_rating
count,396.000000,413.000000,407,413.000000,367.000000
mean,74.218434,2.970944,2026-05-09 07:54:06.191646208,2.677966,2.989101
min,-56.080000,-1.000000,2026-01-01 00:00:00,1.000000,1.000000
25%,23.062500,2.000000,2026-03-04 12:00:00,1.000000,2.000000
50%,38.240000,3.000000,2026-05-03 00:00:00,2.000000,3.000000
75%,65.037500,4.000000,2026-07-17 12:00:00,3.000000,4.000000
max,3499.810000,5.000000,2026-09-27 00:00:00,26.000000,8.000000
std,270.877718,1.479349,NaN,2.809558,1.561102

In [ ]:
data.shape

(413, 10)

In [53]:
data.describe(include='object')

        order_id customer_id   city category payment_method
count        413         413    390      413            400
unique       400         141     20       15              3
top     ORD-1120     CUS-055  Aqaba  Fashion           CliQ
freq           2           9     79       87            138

In [ ]:
data['order_date'] = pd.to_datetime(data['order_date'], format='%Y-%m-%d',errors='coerce')

In [ ]:
data['order_date']

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         413 non-null    object
 1   customer_id      413 non-null    object
 2   city             390 non-null    object
 3   category         413 non-null    object
 4   order_amount     396 non-null    float64
 5   quantity         413 non-null    int64
 6   order_date       407 non-null    datetime64[ns]
 7   payment_method   400 non-null    object
 8   delivery_days    413 non-null    int64
 9   customer_rating  367 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 32.4+ KB

In [ ]:
data.loc[64]

order_id              ORD-1065
customer_id            CUS-122
city                     Aqaba
category           Electronics
order_amount              49.9
quantity                     1
order_date                 NaT
payment_method            Card
delivery_days                5
customer_rating            1.0
Name: 64, dtype: object

In [43]:
num_data = data.select_dtypes(include = 'number')

In [44]:
num_data

     order_amount  quantity  delivery_days  customer_rating
0           52.50         1             26              NaN
1           33.40         2              3              1.0
2           29.50         1              2              3.0
3           23.19         2              1              5.0
4           84.28         5              1              NaN
..            ...       ...            ...              ...
408          9.01         5              3              2.0
409         73.64         5              2              3.0
410          9.93         5              3              1.0
411         39.03         1              2              8.0
412        999.00         4              2              3.0

[413 rows x 4 columns]

In [46]:
qat_data = data.select_dtypes(include = 'object')
qat_data

     order_id customer_id     city     category payment_method
0    ORD-1001     CUS-027    Zarqa      Fashion           Card
1    ORD-1002     CUS-051    Irbid      Fashion           CliQ
2    ORD-1003     CUS-076    Aqaba      Fashion           CliQ
3    ORD-1004     CUS-036   Irbid   Electronics           Card
4    ORD-1005     CUS-075     Salt       Beauty           CliQ
..        ...         ...      ...          ...            ...
408  ORD-1056     CUS-044    Zarqa        Books           Cash
409  ORD-1111     CUS-009    Irbid      Fashion           Card
410  ORD-1250     CUS-125    Aqaba         Home           Card
411  ORD-1319     CUS-109    Amman  Electronics           CliQ
412  ORD-1011     CUS-089    Aqaba       Beauty           CliQ

[413 rows x 5 columns]

In [ ]:
data["city"].unique().tolist()

In [51]:
data['city'].nunique()

20

In [57]:
standardized_city_demo = data["city"].astype("string").str.strip().str.title()
standardized_city_demo.unique()

<StringArray>
['Zarqa', 'Irbid', 'Aqaba', 'Salt', <NA>, 'Amman']
Length: 6, dtype: string

In [59]:
comparison = pd.DataFrame({
    "Version": ["Raw city labels", "Standardized preview"],
    "Distinct values (including missing)": [
        data["city"].nunique(dropna=False),
        standardized_city_demo.nunique(dropna=False),
    ],
})

In [62]:
data.columns.tolist()

['order_id',
 'customer_id',
 'city',
 'category',
 'order_amount',
 'quantity',
 'order_date',
 'payment_method',
 'delivery_days',
 'customer_rating']

In [64]:
data['city'] = standardized_city_demo

In [66]:
data.head()

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
0,ORD-1001,CUS-027,Zarqa,Fashion,52.50,1,2026-06-17,Card,26,NaN
1,ORD-1002,CUS-051,Irbid,Fashion,33.40,2,2026-08-16,CliQ,3,1.0
2,ORD-1003,CUS-076,Aqaba,Fashion,29.50,1,2026-06-12,CliQ,2,3.0
3,ORD-1004,CUS-036,Irbid,Electronics,23.19,2,2026-08-31,Card,1,5.0
4,ORD-1005,CUS-075,Salt,Beauty,84.28,5,2026-05-31,CliQ,1,NaN

In [67]:
data['payment_method'].unique()

array(['Card', 'CliQ', 'Cash', nan], dtype=object)

In [ ]:
data.isna().sum()

In [ ]:
(data.isna().mean() * 100).round(2)

In [76]:
data[data["order_amount"].isna()]

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
33,ORD-1034,CUS-136,Salt,Books,NaN,3,2026-07-11,Cash,4,3.0
52,ORD-1053,CUS-024,Irbid,Electronics,NaN,2,2026-07-05,CliQ,3,5.0
59,ORD-1060,CUS-087,Irbid,Fashion,NaN,1,2026-02-17,CliQ,2,3.0
83,ORD-1084,CUS-025,Amman,Fashion,NaN,4,2026-06-18,Cash,2,5.0
94,ORD-1095,CUS-093,Amman,Electronics,NaN,5,2026-08-26,Card,5,NaN
121,ORD-1122,CUS-100,Zarqa,Fashion,NaN,2,2026-06-16,Card,3,1.0
146,ORD-1147,CUS-089,Zarqa,Home,NaN,2,2026-09-05,Card,2,NaN
173,ORD-1174,CUS-121,Zarqa,Electronics,NaN,3,2026-01-15,Card,1,4.0
189,ORD-1190,CUS-056,Zarqa,Books,NaN,3,2026-04-12,Cash,2,NaN
234,ORD-1235,CUS-012,<NA>,Home,NaN,3,2026-05-08,Cash,3,3.0
237,ORD-1238,CUS-096,Aqaba,books,NaN,5,2026-04-13,Card,2,2.0
239,ORD-1240,CUS-044,Irbid,Electronics,NaN,5,NaT,Cash,2,5.0
334,ORD-1335,CUS-024,Zarqa,Books,NaN,5,2026-08-05,CliQ,1,5.0
344,ORD-1345,CUS-034,Salt,Books,NaN,1,2026-08-29,CliQ,1,5.0
382,ORD-1383,CUS-114,Aqaba,Electronics,NaN,1,2026-03-06,CliQ,1,2.0
391,ORD-1392,CUS-104,Irbid,Books,NaN,4,2026-05-03,Card,1,1.0
402,ORD-1392,CUS-104,Irbid,Books,NaN,4,2026-05-03,Card,1,1.0

In [77]:
data.isna().any(axis=1)

0       True
1      False
2      False
3      False
4       True
       ...
408    False
409    False
410    False
411    False
412    False
Length: 413, dtype: bool